input:
  # Distances between bacterial isolates (mash table)
  - input/distances.tab
  # Bacterial metadata (capsule & ST)
  - input/KASPAH.csv
   # Directory to annotated prophages in genbank format (seperate file) found in isolates that were used to build a tree.
  - input/phages-fasta-KASPAH99

output_dir:
  - output

# Lineage definition: 0.01 or 0.004
lineage_cutoff:
  - 0.004

# gbk by default.
files_extension:
  - fasta

phage_variants:
  min_pid:
    - 0.9
  min_subject_cov:
    - 0.9
  min_query_cov:
    - 0.9

receptor_binding_proteins:
  aa_pid:
    - 0.75
  aa_cov:
    - 0.8
  rbp_key_phrases:
    - tail fiber protein
    - rna ligase and tail fiber protein attachment catalyst
    - long tail fiber protein distal subunit
    - tail collar fiber protein
    - tail fiber protein proximal subunit
    - long tail fiber protein proximal connector
    - hinge connector of long tail fiber protein distal connector
    - short tail fiber protein
    - lytic tail fiber protein
    - tail fiber protein; host specificity
    - tail fiber protein/ lysozyme
    - baseplate wedge tail fiber protein connector
    - tail fiber protein and host specificity
    - tail fiber protein; ig-domain containing
    - tail spike protein
    - pentameric base spike protein
    - tail spike protein with colonic acid degradation activity
